version: "2"

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  web:
    build: ./web/
    ports:
      - "89:80"
    links:
      - banco:banco
      - banco2:banco2
    volumes:
      - ./app:/var/www/html
    networks:
      mynet:
       ipv4_address: 172.18.0.2

  banco:
    image: mysql
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa
    networks:
      mynet:
        ipv4_address: 172.18.0.3

  banco2:
    image: postgres
    restart: always
    ports:
      - "5439:5432"
    environment:
      POSTGRES_PASSWORD: senha_da_nasa
      POSTGRES_USER: hh_user
    networks:
      mynet:
        ipv4_address: 172.18.0.4

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - banco:banco
      - banco2:banco2
    networks:
      mynet:
        ipv4_address: 172.18.0.5


   





